name: Java CI

on:
  push:
  pull_request_target:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin' # AdoptOpenJDK тепер Temurin
          cache: maven            # Увімкнене кешування Maven

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

      - name: Approve if successful
        if: ${{ github.event.pull_request && success() }}
        uses: mate-academy/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reject if failed
        if: ${{ github.event.pull_request && failure() }}
        uses: mate-academy/auto-reject-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
